apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: nodeapp-ingress

  annotations:

    nginx.ingress.kubernetes.io/rewrite-target: /

spec:

  ingressClassName: nginx-example

  rules:

  - http:

      paths:

      - path: /nodeapp

        pathType: Prefix

        backend:

          service:

            name: nodeapp-service

            port:

              number: 3000
